import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  storyBg: {
    backgroundColor: "#181a1c",
    overflow: "hidden",
  },
  iconLayout: {
    width: 32,
    height: 32,
  },
  backIcon1: {
    top: 184,
    left: 319,
    backgroundColor: "#181a1c",
  },
  iconArrowLeft: {
    width: 16,
    height: 16,
    overflow: "hidden",
  },
  backIcon: {
    top: 60,
    backgroundColor: "#000",
    left: 24,
    padding: 8,
  },
  backIconBorder: {
    padding: 8,
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 30,
    borderColor: "#323436",
    borderStyle: "solid",
    flexDirection: "row",
    justifyContent: "center",
    position: "absolute",
  },
  tabbarPosition: {
    left: 24,
    position: "absolute",
  },
  postsTypo: {
    textAlign: "center",
    fontFamily: "HK Grotesk",
  },
  kFollowersLayout: {
    lineHeight: 18,
    textAlign: "left",
  },
  oumaPosition: {
    left: "30%",
    top: 251,
    position: "absolute",
  },
  timeLayout: {
    lineHeight: 20,
    textAlign: "center",
  },
  borderBorder: {
    borderWidth: 1,
    borderStyle: "solid",
  },
  photoLayout: {
    height: 150,
    width: 150,
    position: "absolute",
  },
  storyPosition: {
    left: 0,
    top: 0,
  },
  timePosition: {
    left: "0%",
    position: "absolute",
  },
  capacityBg: {
    backgroundColor: "#fff",
    position: "absolute",
  },
  profileFlexBox: {
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  backIconFlexBox: {
    borderRadius: 30,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  contentSpaceBlock: {
    paddingVertical: 0,
    paddingHorizontal: 24,
    justifyContent: "center",
  },
  posts: {
    color: "#fff",
    fontWeight: "700",
    lineHeight: 16,
    fontSize: 13,
  },
  stories: {
    marginLeft: 60,
    color: "#fff",
    lineHeight: 16,
    fontSize: 13,
  },
  options: {
    flexDirection: "row",
  },
  divider1: {
    borderTopWidth: 1,
    width: 328,
    height: 1,
    borderColor: "#323436",
    borderStyle: "solid",
  },
  selectedTab: {
    borderColor: "#2e8af6",
    borderTopWidth: 4,
    width: 43,
    height: 4,
    borderStyle: "solid",
  },
  divider: {
    marginTop: 12,
  },
  tabbar: {
    top: 477,
    justifyContent: "center",
  },
  followedByChild: {
    left: 0,
    top: 0,
    position: "absolute",
  },
  followedByItem: {
    left: 14,
    top: 0,
    position: "absolute",
  },
  followedByInner: {
    left: 28,
    top: 0,
    position: "absolute",
  },
  ellipseIcon: {
    left: 43,
    top: 0,
    position: "absolute",
  },
  followedBySofia: {
    top: 7,
    left: 82,
    opacity: 0.6,
    textAlign: "left",
    color: "#fff",
    fontFamily: "HK Grotesk",
    fontSize: 13,
    position: "absolute",
  },
  followedBy: {
    top: 421,
    width: 303,
    height: 32,
    left: 24,
    position: "absolute",
  },
  ouma: {
    left: 137,
    fontSize: 18,
    lineHeight: 32,
    textAlign: "center",
    fontFamily: "HK Grotesk",
    color: "#fff",
    fontWeight: "700",
  },
  mateurMa: {
    top: 285,
    left: 175,
    color: "#727477",
    fontWeight: "600",
    lineHeight: 16,
    fontSize: 13,
    position: "absolute",
  },
  iDesignExperiences: {
    top: 309,
    width: 327,
    color: "#ecebed",
    fontSize: 14,
    fontFamily: "HK Grotesk",
    left: 35,
    position: "absolute",
  },
  profileBannerIcon: {
    height: 160,
    top: 0,
    overflow: "hidden",
  },
  story: {
    borderRadius: 100,
    left: 0,
    top: 0,
    overflow: "hidden",
    backgroundColor: "#181a1c",
  },
  profilePhotoIcon: {
    top: 5,
    left: 5,
    width: 140,
    height: 140,
    borderRadius: 100,
    position: "absolute",
    overflow: "hidden",
  },
  photo: {
    top: 85,
    left: 113,
  },
  messageIcon: {
    bottom: -95,
    left: 280,
    borderRadius: 32,
    width: 32,
    height: 32,
  },
  border: {
    height: "100%",
    width: "90.43%",
    top: "0%",
    right: "9.57%",
    bottom: "0%",
    borderRadius: 3,
    borderColor: "#fff",
    opacity: 0.35,
    borderWidth: 1,
    borderStyle: "solid",
    left: "0%",
  },
  capIcon: {
    height: "35.29%",
    width: "5.46%",
    top: "32.35%",
    right: "0%",
    bottom: "32.35%",
    left: "94.54%",
    maxWidth: "100%",
    maxHeight: "100%",
    opacity: 0.4,
    position: "absolute",
    overflow: "hidden",
  },
  capacity: {
    height: "64.71%",
    width: "73.99%",
    top: "17.65%",
    right: "17.79%",
    bottom: "17.65%",
    left: "8.22%",
    borderRadius: 1,
  },
  battery: {
    height: "25.76%",
    width: "6.49%",
    top: "39.39%",
    right: "3.82%",
    bottom: "34.85%",
    left: "89.69%",
    position: "absolute",
  },
  wifiIcon: {
    width: 15,
    height: 11,
  },
  cellularConnectionIcon: {
    width: 17,
    height: 11,
  },
  time: {
    marginTop: -4.5,
    top: "50%",
    fontSize: 15,
    letterSpacing: 0,
    fontFamily: "SF Pro Text",
    lineHeight: 20,
    textAlign: "center",
    fontWeight: "600",
    color: "#fff",
    width: "100%",
  },
  timeStyle: {
    height: "47.73%",
    width: "14.4%",
    top: "15.91%",
    right: "80%",
    bottom: "36.36%",
    left: "5.6%",
    position: "absolute",
  },
  barsStatusBarIphoneL: {
    right: 0,
    height: 44,
    position: "absolute",
  },
  k1: {
    fontFamily: "HK Grotesk",
    fontWeight: "700",
  },
  k: {
    color: "#fff",
  },
  followers1: {
    color: "#727477",
  },
  followers: {
    fontWeight: "600",
    fontFamily: "HK Grotesk",
  },
  kFollowers: {
    fontSize: 14,
    textAlign: "left",
  },
  k2: {
    color: "#fff",
    fontFamily: "HK Grotesk",
    fontWeight: "700",
  },
  following: {
    color: "#727477",
    fontWeight: "600",
    fontFamily: "HK Grotesk",
  },
  buttonLabel: {
    textAlign: "center",
    fontFamily: "HK Grotesk",
    color: "#fff",
    fontWeight: "700",
  },
  ctaPrimaryDefault: {
    backgroundColor: "#f62e8e",
    paddingHorizontal: 32,
    paddingVertical: 6,
    alignItems: "center",
    borderRadius: 30,
    justifyContent: "center",
  },
  profileActions: {
    top: 369,
    width: 327,
    left: 24,
    position: "absolute",
  },
  backIcon1: {
    top: 184,
    left: 319,
    backgroundColor: "#181a1c",
  },
  profilePhotoIcon1: {
    borderRadius: 100,
    overflow: "hidden",
  },
  ouma1: {
    color: "#ecebed",
    fontSize: 14,
    textAlign: "left",
    fontFamily: "HK Grotesk",
    fontWeight: "700",
    lineHeight: 16,
  },
  hAgo: {
    marginTop: 2,
    fontSize: 12,
    textAlign: "left",
    lineHeight: 16,
    color: "#727477",
  },
  oumaParent: {
    marginLeft: 8,
  },
  info: {
    justifyContent: "center",
  },
  iconDotsVertical: {
    width: 24,
    height: 24,
    overflow: "hidden",
  },
  profileInfo: {
    alignSelf: "stretch",
  },
  carouselItem: {
    marginLeft: 12,
  },
  carousel: {
    marginTop: 16,
    width: 327,
  },
  carouselIndicatorChild: {
    marginLeft: 10,
  },
  carouselIndicator: {
    marginTop: 16,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  text1: {
    marginLeft: 8,
    fontWeight: "600",
    color: "#fff",
    fontFamily: "HK Grotesk",
  },
  comment: {
    marginLeft: 20,
    justifyContent: "center",
  },
  iconBookmark: {
    width: 20,
    height: 20,
    overflow: "hidden",
  },
  postActions: {
    marginTop: 16,
    width: 327,
  },
  content: {
    width: 327,
    justifyContent: "center",
  },
  divider2: {
    borderTopWidth: 2,
    height: 2,
    marginTop: 16,
    alignSelf: "stretch",
  },
  post1: {
    top: 529,
    overflow: "hidden",
  },
  toAllThe: {
    color: "#ecebed",
  },
  readMore: {
    textDecoration: "underline",
    color: "#f62e8e",
    fontFamily: "HK Grotesk",
    fontWeight: "700",
  },
  toAllTheContainer: {
    marginTop: 16,
    alignSelf: "stretch",
    textAlign: "left",
  },
  content1: {
    paddingHorizontal: 24,
    paddingVertical: 0,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  post2: {
    top: 849,
  },
  homeIndicator: {
    marginLeft: -66.5,
    bottom: 8,
    left: "50%",
    width: 134,
    height: 5,
    borderRadius: 100,
  },
  mobilehomeIndicatorLight: {
    top: 1121,
    left: -12,
    height: 24,
  },
  profileUserBeforeCoach: {
    flex: 1,
    height: 1173,
    overflow: "hidden",
    width: "100%",
    backgroundColor: "#181a1c",
  },
  cTAPrimaryDefault: {
    flexShrink: 0,
    backgroundColor: "rgba(24, 26, 28, 1)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    columnGap: 10,
    paddingVertical: 6,
    paddingHorizontal: 32,
    borderWidth: 1,
    borderColor: "rgba(114, 116, 119, 1)",
    borderRadius: 30
    },
    buttonLabel: {
    flexShrink: 0,
    textAlign: "center",
    color: "rgba(255, 255, 255, 1)",
    fontFamily: "HK Grotesk",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 24
    },
    post: {
      backgroundColor: '#181a1c',
      marginBottom: 20,
      borderRadius: 10,
      padding: 15,
    },
    profileInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    profilePhoto: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 10,
    },
    profileText: {
      flex: 1,
    },
    profileName: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 16,
    },
    timeAgo: {
      color: '#727477',
      fontSize: 12,
    },
    greeting: {
      color: '#ecebed',
      fontSize: 14,
      marginBottom: 10,
    },
    postImage: {
      width: '100%',
      height: 200,
      borderRadius: 10,
      marginBottom: 10,
    },
    actions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    action: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    likeCount: {
      marginLeft: 5,
      color: '#fff',
      fontSize: 14,
    },
    commentCount: {
      marginLeft: 5,
      color: '#fff',
      fontSize: 14,
    },
    commentInput: {
      backgroundColor: '#323436',
      color: '#fff',
      borderRadius: 10,
      padding: 10,
    },
    dropdownButton: {
      marginLeft: 'auto',
    },
});

export default styles;
